### ISSUE TITLE
Color issue

### ISSUE THREAD

**Issue by Saee1799** [ajency/ccir-report#2]
Can you change the color of this separator line to #006685

![image](https://user-images.githubusercontent.com/96518669/216582855-e46e7213-5675-4ce6-acff-ff7a087bf940.png)

**Comment by MamataNivajekar** [comment]
@Saee1799 Separator line color is already #006685

![image](https://user-images.githubusercontent.com/81617777/217481945-4da23af5-034c-4487-b7fa-ff366bd7721f.png)

**Comment by Saee1799** [comment]
okay got it @MamataNivajekar
