### ISSUE TITLE
text arrangement

### ISSUE THREAD

**Issue by Saee1799** [ajency/ccir-report#30]
please arrange the 30+ in 6M and 90+ in 12M text on two lines instead of three.
Refer to the same columns in the total account which is highlighted in the black box in the below screenshot

![image](https://user-images.githubusercontent.com/96518669/217737024-8d1140e3-fd80-4ae0-8b82-e8eb38808181.png)

**Comment by MamataNivajekar** [comment]
@Saee1799 I have tried to arrange most of the columns, but the above arrangement is not possible due to screen/table width limitations.

**Comment by Saee1799** [comment]
understood
